################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
NAME        = "zprotut"
VERSION     = "1.1.0"
LICENSE     = "mit"
DESCRIPTION = """Python bindings of: project"""
URL         = "https://github.com/dertom95/zproject-tutorial.git"
PACKAGES    = ["zprotut"]
REQUIRES    = [
]
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
