/*  =========================================================================
    gs - generated layer of public API

    Copyright (c) the Authors

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef GS_LIBRARY_H_INCLUDED
#define GS_LIBRARY_H_INCLUDED

//  Set up environment for the application

//  External dependencies

//  GS version macros for compile-time API detection
#define GS_VERSION_MAJOR 1
#define GS_VERSION_MINOR 1
#define GS_VERSION_PATCH 0

#define GS_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define GS_VERSION \
    GS_MAKE_VERSION(GS_VERSION_MAJOR, GS_VERSION_MINOR, GS_VERSION_PATCH)

// czmq_prelude.h bits
#if !defined (__WINDOWS__)
#   if (defined WIN32 || defined _WIN32 || defined WINDOWS || defined _WINDOWS)
#       undef __WINDOWS__
#       define __WINDOWS__
#   endif
#endif

// Windows MSVS doesn't have stdbool
#if (defined (_MSC_VER) && !defined (true))
#   if (!defined (__cplusplus) && (!defined (true)))
#       define true 1
#       define false 0
        typedef char bool;
#   endif
#else
#   include <stdbool.h>
#endif
// czmq_prelude.h bits

#if defined (__WINDOWS__)
#   if defined GS_STATIC
#       define GS_EXPORT
#   elif defined GS_INTERNAL_BUILD
#       if defined DLL_EXPORT
#           define GS_EXPORT __declspec(dllexport)
#       else
#           define GS_EXPORT
#       endif
#   elif defined GS_EXPORTS
#       define GS_EXPORT __declspec(dllexport)
#   else
#       define GS_EXPORT __declspec(dllimport)
#   endif
#   define GS_PRIVATE
#elif defined (__CYGWIN__)
#   define GS_EXPORT
#   define GS_PRIVATE
#else
#   if (defined __GNUC__ && __GNUC__ >= 4) || defined __INTEL_COMPILER
#       define GS_PRIVATE __attribute__ ((visibility ("hidden")))
#       define GS_EXPORT __attribute__ ((visibility ("default")))
#   else
#       define GS_PRIVATE
#       define GS_EXPORT
#   endif
#endif

//  Project has no stable classes, so we build the draft API
#undef  GS_BUILD_DRAFT_API
#define GS_BUILD_DRAFT_API

//  Opaque class structures to allow forward references
//  These classes are stable or legacy and built in all releases
//  Draft classes are by default not built in stable releases
#ifdef GS_BUILD_DRAFT_API
typedef struct _shouter_t shouter_t;
#define SHOUTER_T_DEFINED
#endif // GS_BUILD_DRAFT_API


//  Public classes, each with its own header file
#ifdef GS_BUILD_DRAFT_API
#include "shouter.h"
#endif // GS_BUILD_DRAFT_API

#ifdef GS_BUILD_DRAFT_API

#ifdef __cplusplus
extern "C" {
#endif

//  Self test for private classes
GS_EXPORT void
    gs_private_selftest (bool verbose, const char *subtest);

#ifdef __cplusplus
}
#endif
#endif // GS_BUILD_DRAFT_API

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/
